[package]
name = "zygal-prompt"
version = "0.0.1-alpha.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
regex = "1.11.1"

[features]
default = ["zsh"]
zsh = []

[dev-dependencies]
asserting = "0.9.0"
tempdir = "0.3.7"
