#!/bin/sh

ZYGAL_ASYNC="${ZYGAL_ASYNC:-remote}"

ZYGAL_ENABLE_VCS_REMOTE="${ZYGAL_ENABLE_VCS_REMOTE-true}"
$ZYGAL_ENABLE_VCS_REMOTE && {
    ZYGAL_VCS_REMOTE_SYNC_TRIGGER="${ZYGAL_VCS_REMOTE_REFRESH_COUNT:-10}"
    ZYGAL_VCS_REMOTE_COUNT=-1
}

ZYGAL_COLORSCHEME=${ZYGAL_COLORSCHEME:-orange}
