name: Continuous integration

on:
  push:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: 'true'

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo build output
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ./zygal/target
        key: cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Format
      run: cargo fmt --check
      working-directory: ./zygal

    - name: Lint
      run: cargo clippy
      working-directory: ./zygal

    - name: Build
      run: cargo build
      working-directory: ./zygal

    - name: Test
      run: cargo test
      working-directory: ./zygal
